version: '3.8'

services:

  postgres:
    image: postgres
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: JoaoGuilherme2601
      POSTGRES_USER: postgres
      POSTGRES_DB: cliente
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql

  adminer:
    image: adminer
    restart: always
    container_name: meu-adminer
    ports:
      - 8080:8080

volumes:
  postgres-data:

