apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: customer-namespace
spec:
  selector:
    app: customer-ms
  ports:
    - port: 80
      targetPort: 8989
  type: LoadBalancer