name: Open PR to Develop

on:
  create:
    branches:
      - 'feature/*'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Create PR to develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_TITLE="Merge ${{ env.BRANCH_NAME }} to develop"
          PR_BODY="This PR merges the ${{ env.BRANCH_NAME }} branch to develop"
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --head "${{ env.BRANCH_NAME }}" --base develop
